apiVersion: v1
kind: Service
metadata:
  name: hello-nginx-svc
  namespace: hello-namespace
spec:
  type: NodePort
  selector:
    app: hello-nginx
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30801
